
INSERT INTO `activities` (`id`, `area_id`, `habilities_id`, `name`, `description`) VALUES
(1, 1, 1, 'Come con la mano', ''),
(2, 1, 1, 'Bebe con vaso y/o taza', ''),
(3, 1, 1, 'Utiliza cubiertos', ''),
(4, 1, 1, 'Pone y retira la mesa para sí', ''),
(5, 1, 1, 'Sacude migajas y/o limpia líquidos o comida derramada', ''),
(6, 1, 1, 'Saca alimentos de la despensa o del refrigerador', ''),
(7, 1, 1, 'Prepara alimentos sencillos para sí: Fríos', ''),
(8, 1, 1, 'Prepara alimentos sencillos para sí: Calientes', ''),
(9, 1, 2, 'Quita ropa parte inferior', ''),
(10, 1, 2, 'Quita ropa parte superior', ''),
(11, 1, 2, 'Pone ropa parte superior', ''),
(12, 1, 2, 'Pone ropa parte inferior', ''),
(13, 1, 2, 'Abotona, acordona, utiliza cierres y/o broches', ''),
(14, 1, 2, 'Al vestirse se da cuenta que las prendas están bien colocadas', ''),
(15, 1, 2, 'Distingue ropa limpia o sucia', ''),
(16, 1, 2, 'Distingue qué ropa usar según el clima', ''),
(17, 1, 3, 'Habituación', ''),
(18, 1, 3, 'Avisa si ensució su pañal', ''),
(19, 1, 3, 'Controla salivación', ''),
(20, 1, 3, 'Controla esfínteres', ''),
(21, 1, 3, 'Utiliza correctamente WC', ''),
(22, 1, 3, 'Realiza higiene personal', ''),
(23, 1, 3, 'Se baña y /o lava su pelo', ''),
(24, 1, 3, 'Se maquilla y /o rasura distintas partes de su cuerpo', ''),
(25, 1, 3, 'Conoce los cuidados específicos de distintas partes de su cuerpo', ''),
(26, 1, 3, 'Conoce y/o maneja su sexualidad', ''),
(27, 1, 3, 'Usa condón/anticonceptivos', ''),
(28, 2, 4, 'Reconoce ropa limpia y sucia', ''),
(29, 2, 4, 'Lava ropa a mano', ''),
(30, 2, 4, 'Lava ropa a máquina', ''),
(31, 2, 4, 'Tiende, plancha y/o guarda la ropa', ''),
(32, 2, 4, 'Repara la ropa', ''),
(33, 2, 4, 'Elige su ropa diaria (según clima)', ''),
(34, 2, 4, 'Compra su propia ropa (negocio y/o catálogo)', ''),
(35, 2, 5, 'Guarda en alacena, refrigerador y/o estantes', ''),
(36, 2, 5, 'Prepara recetas sencillas', ''),
(37, 2, 5, 'Usa distintos modos de cocción', ''),
(38, 2, 5, 'Reconoce el buen estado de los alimentos', ''),
(39, 2, 5, 'Puede balancear su dieta', ''),
(40, 2, 5, 'Realiza listas de mandados', ''),
(41, 2, 5, 'Realiza compras', ''),
(42, 2, 6, 'Barre, trapea y/o sacude', ''),
(43, 2, 6, 'Lava ventanas', ''),
(44, 2, 6, 'Lava y ordena trastes', ''),
(45, 2, 6, 'Limpia la estufa y/o refrigerador', ''),
(46, 2, 6, 'Destiende y/o tiende la cama', ''),
(47, 2, 6, 'Lava muebles del baño', ''),
(48, 2, 7, 'Utiliza el teléfono', ''),
(49, 2, 7, 'Utiliza aparatos eléctricos', ''),
(50, 2, 7, 'Reconoce y/o soluciona situaciones de riesgo', ''),
(51, 2, 7, 'Cambia focos y/o destapa drenajes', ''),
(52, 2, 7, 'Realiza cambios de la silla de ruedas a la cama y/o el inodoro', ''),
(53, 3, 8, 'Tiene en su casa tareas asignadas (recoger, limpiar, lavar, sacudir)', ''),
(54, 3, 8, 'Sabe cuáles son sus actividades diarias', ''),
(55, 3, 8, 'Conoce su dirección particular', ''),
(56, 3, 8, 'Reconoce horarios y fechas', ''),
(57, 3, 8, 'Conoce el uso del reloj', ''),
(58, 3, 8, 'Regula tiempos y puntualidad', ''),
(59, 3, 8, 'Avisa en caso de retrasos', ''),
(60, 3, 8, 'Conoce su agenda semanal', ''),
(61, 3, 8, 'Administra su medicación', ''),
(62, 3, 8, 'Maneja calendario', ''),
(63, 3, 8, 'Conoce y/o recuerda fechas familiares', ''),
(64, 3, 8, 'Realiza recorridos habituales', ''),
(65, 3, 8, 'Planifica actividades de ocio', ''),
(66, 3, 8, 'Organiza sus reuniones y/o salidas', ''),
(67, 3, 8, 'Conoce sus derechos y obligaciones', ''),
(68, 4, 9, 'Reconoce trayectos habituales', ''),
(69, 4, 9, 'Se traslada a lugares cercanos y/o lejanos', ''),
(70, 4, 9, 'Utiliza medios de transporte', ''),
(71, 4, 9, 'Conoce trayectos alternativos a los habituales', ''),
(72, 4, 9, 'Maneja dinero', ''),
(73, 4, 9, 'Realiza compras', ''),
(74, 4, 9, 'Reconoce el centro de salud más cercano', ''),
(75, 4, 9, 'Conoce recursos y servicios de su comunidad', ''),
(76, 4, 9, 'Sabe solicitar turnos médicos', ''),
(77, 4, 9, 'Sabe marcar teléfonos de emergencia', ''),
(78, 4, 9, 'Identifica y/o previene situaciones de riesgo', ''),
(79, 4, 9, 'Reconoce señales viales y preventivas', ''),
(80, 4, 9, 'Participa en actividades de su comunidad', ''),
(81, 4, 9, 'Utiliza INE vigente', ''),
(82, 4, 9, 'Vota', ''),
(83, 5, 10, 'Responde cuando escucha su nombre', ''),
(84, 5, 10, 'En actividades cotidianas sigue con la mirada los objetos que se le presentan', ''),
(85, 5, 10, 'Es capaz de imitar gestos, sonidos y acciones', ''),
(86, 5, 10, 'Conoce las partes de su cuerpo, las señala, nombra o mueve e identifica su función', ''),
(87, 5, 10, 'Emplea nociones espaciales para contextualizarse en el entorno', ''),
(88, 5, 10, 'Emplea las nociones temporales para la realización de sus actividades diarias', ''),
(89, 5, 10, 'Hace uso de las nociones de medida para resolver problemas sencillos de la vida cotidiana', ''),
(90, 5, 10, 'Identifica y clasifica objetos cotidianos por tamaño, forma y color', ''),
(91, 5, 10, 'Realiza trazos dentro de espacios determinados', ''),
(92, 5, 10, 'Puede escribir o copiar su nombre', ''),
(93, 5, 10, 'Escribe sílabas, palabras y enunciados (con las reglas de separación)', ''),
(94, 5, 10, 'Presenta escritura espontánea', ''),
(95, 5, 10, 'Visualiza una imagen y le da significado', ''),
(96, 5, 10, 'Reconoce grafías (vocales y consonantes)', ''),
(97, 5, 10, 'Lee (sílabas, palabras, enunciados y textos)', ''),
(98, 5, 10, 'Realiza la lectura de textos y los comprende', ''),
(99, 5, 10, 'Distingue el número de las letras', ''),
(100, 5, 10, 'Reconoce el uso de números en la vida cotidiana', ''),
(101, 5, 10, 'Reconoce y señala números del 0 al 10', ''),
(102, 5, 10, 'Ordena una secuencia de números', ''),
(103, 5, 10, 'Tiene conteo uno a uno hasta el número 10 y lo aplica a la vida cotidiana', ''),
(104, 5, 10, 'Resuelve algoritmos sencillos de 1 y 2 dígitos', ''),
(105, 5, 10, 'Resuelve problemas de la vida diaria (de adición y sustracción)', ''),
(106, 5, 10, 'Al resolver problemas analiza la información, identifica y resuelve operaciones', ''),
(107, 5, 10, 'Utiliza la tecnología para aplicarla en las actividades académicas', ''),
(108, 6, 11, 'Responde a estímulos V-A-T', ''),
(109, 6, 11, 'Presenta patrón básico de respuesta', ''),
(110, 6, 11, 'Expresa placer-displacer', ''),
(111, 6, 11, 'Reconoce y expresa emociones', ''),
(112, 6, 11, 'Maneja código elemental de comunicación', ''),
(113, 6, 11, 'Se expresa: Por facies', ''),
(114, 6, 11, 'Se expresa: Movimiento ocular', ''),
(115, 6, 11, 'Se expresa: Gesticulación', ''),
(116, 6, 11, 'Se expresa: Señala', ''),
(117, 6, 11, 'Habla', ''),
(118, 6, 11, 'Tablero de comunicación', ''),
(119, 6, 11, 'Lengua de señas', ''),
(120, 6, 11, 'Lenguaje escrito / Braille', ''),
(121, 6, 11, 'Expresión corporal', ''),
(122, 6, 11, 'Estructura enunciados', ''),
(123, 6, 11, 'Reconoce y respeta códigos sociales', ''),
(124, 6, 11, 'Reconoce bromas o absurdos', ''),
(125, 6, 11, 'Mantiene comunicación en distintos entornos', ''),
(126, 6, 11, 'Mantiene comunicación por distintos medios', ''),
(127, 7, 12, 'Sigue objetos y/o se conecta al entorno', ''),
(128, 7, 12, 'Presenta destrezas motrices generales', ''),
(129, 7, 12, 'Arrastra y/o empuja objetos', ''),
(130, 7, 12, 'Realiza juegos simbólicos', ''),
(131, 7, 12, 'Participa en juegos tradicionales ¿con quién?', ''),
(132, 7, 12, 'Participa en juegos de mesa ¿con quién?', ''),
(133, 7, 12, 'Realiza actividades preferidas en el hogar', ''),
(134, 7, 12, 'Realiza actividades preferidas en el exterior', ''),
(135, 7, 12, 'Realiza deportes', ''),
(136, 7, 12, 'Participa en actividades de arte', ''),
(137, 7, 12, 'Conoce la actualidad de su ciudad y/o país', ''),
(138, 7, 12, 'Utiliza servicios de ocio de su comunidad', ''),
(139, 7, 12, 'Participa en forma permanente o esporádica en actividades de su comunidad', ''),
(140, 8, 13, 'Presenta / responde gestos sociales básicos', ''),
(141, 8, 13, 'Presenta normas básicas de cortesía', ''),
(142, 8, 13, 'Expresa asertivamente su desagrado', ''),
(143, 8, 13, 'Reconoce / expresa sentimientos', ''),
(144, 8, 13, 'Reconoce y respeta componentes verbales y no verbales de la comunicación', ''),
(145, 8, 13, 'Inicia y mantiene relaciones', ''),
(146, 8, 13, 'Diferencia pautas sociales según grupos y entornos', ''),
(147, 8, 13, 'Se defiende o busca ayuda en situaciones de peligro o agresión', ''),
(148, 8, 13, 'Respeta y aguarda turnos', ''),
(149, 8, 13, 'Reconoce y respeta a autoridades', ''),
(150, 8, 13, 'Reconoce y repara un error y/o pide disculpas', ''),
(151, 8, 13, 'Organiza sus actividades sociales', ''),
(152, 8, 13, 'Pertenece a grupos de su edad', ''),
(153, 9, 14, 'Sigue instrucciones simples/complejas', ''),
(154, 9, 14, 'Conoce, imita o anticipa gestos profesionales', ''),
(155, 9, 14, 'Cuida materiales y elementos', ''),
(156, 9, 14, 'Mantiene orden en su ámbito y elementos', ''),
(157, 9, 14, 'Acepta indicaciones', ''),
(158, 9, 14, 'Cumple normas de trabajo', ''),
(159, 9, 14, 'Recuerda y/o respeta secuencias', ''),
(160, 9, 14, 'Presenta resistencia a la fatiga', ''),
(161, 9, 14, 'Atiende acorde a las demandas del empleo', ''),
(162, 9, 14, 'Presenta habilidades sociales necesarias: con los compañeros', ''),
(163, 9, 14, 'Presenta habilidades sociales necesarias: con los superiores', ''),
(164, 9, 14, 'Respeta horarios', ''),
(165, 9, 14, 'Avisa ante inasistencias', ''),
(166, 9, 14, 'Solicita autorizaciones', ''),
(167, 9, 14, 'Enfrenta acertadamente situaciones problemáticas y solicita ayuda', ''),
(168, 9, 14, 'Reconoce/previene riesgos de sus acciones', ''),
(169, 9, 14, 'Realiza solo el trayecto desde su casa', ''),
(170, 9, 14, 'Porta y conoce uso de la identificación', ''),
(171, 10, 15, 'Presenta reacciones instintivas ante el peligro', ''),
(172, 10, 15, 'Reconoce sensaciones de malestar', ''),
(173, 10, 15, 'Señala si se siente mal', ''),
(174, 10, 15, 'Identifica situaciones de peligro y las evita', ''),
(175, 10, 15, 'Toma medicamentos en los horarios indicados', ''),
(176, 10, 15, 'Templa adecuadamente el agua para el baño', ''),
(177, 10, 15, 'Denuncia las agresiones que sufre', ''),
(178, 10, 15, 'Dice no a propuestas inconvenientes', ''),
(179, 10, 15, 'Reconoce alimentos en mal estado', ''),
(180, 10, 15, 'Anticipa situaciones de riesgo en distintos entornos', ''),
(181, 10, 15, 'Identifica situaciones de riesgo en distintos entornos', ''),
(182, 10, 15, 'Lee fechas de vencimiento', '');